// Generated by CoffeeScript 1.8.0
(function() {
  var ready;

  ready = function() {
    return alert("asaaaaaaaaaap");
  };

  $(document).ready(ready);

  $(document).on('page:load', ready);

}).call(this);
